#!/usr/bin/env python3
"""
Generate graphs and metrics from simulation CSV outputs.

This script reads CSV files generated by data_collection_tree.py and creates
visualizations for network performance metrics.
"""

import csv
import matplotlib.pyplot as plt
import numpy as np
from collections import defaultdict
import os
import sys

# Set style for better-looking graphs
plt.style.use('seaborn-v0_8-darkgrid')
plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['font.size'] = 10

def read_csv(filename):
    """Read CSV file and return list of dicts."""
    if not os.path.exists(filename):
        print(f"⚠️  Warning: {filename} not found. Skipping...")
        return []
    data = []
    with open(filename, 'r', newline='') as f:
        reader = csv.DictReader(f)
        for row in reader:
            data.append(row)
    return data

def graph_1_join_times():
    """Graph 1: Time to join the network (histogram and CDF)."""
    data = read_csv("registration_log.csv")
    if not data:
        return
    
    join_times = [float(row['delta_time']) for row in data if row.get('delta_time')]
    if not join_times:
        print("⚠️  No join times found in registration_log.csv")
        return
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    
    # Histogram
    ax1.hist(join_times, bins=30, edgecolor='black', alpha=0.7, color='steelblue')
    ax1.set_xlabel('Join Time (simulation seconds)', fontsize=12)
    ax1.set_ylabel('Number of Nodes', fontsize=12)
    ax1.set_title('Distribution of Node Join Times', fontsize=14, fontweight='bold')
    ax1.axvline(np.mean(join_times), color='red', linestyle='--', linewidth=2, 
                label=f'Mean: {np.mean(join_times):.2f}s')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    # CDF
    sorted_times = np.sort(join_times)
    cdf = np.arange(1, len(sorted_times) + 1) / len(sorted_times)
    ax2.plot(sorted_times, cdf * 100, linewidth=2, color='steelblue')
    ax2.set_xlabel('Join Time (simulation seconds)', fontsize=12)
    ax2.set_ylabel('Cumulative % of Nodes', fontsize=12)
    ax2.set_title('CDF of Node Join Times', fontsize=14, fontweight='bold')
    ax2.grid(True, alpha=0.3)
    ax2.axvline(np.mean(join_times), color='red', linestyle='--', linewidth=2,
                label=f'Mean: {np.mean(join_times):.2f}s')
    ax2.axhline(50, color='gray', linestyle=':', alpha=0.5, label='50%')
    ax2.legend()
    
    plt.tight_layout()
    plt.savefig('graph_1_join_times.png', dpi=300, bbox_inches='tight')
    print("✅ Graph 1 saved: graph_1_join_times.png")
    plt.close()
    
    # Print stats
    print(f"\n📊 Join Time Statistics:")
    print(f"   Average: {np.mean(join_times):.4f} sim seconds")
    print(f"   Min: {np.min(join_times):.4f} sim seconds")
    print(f"   Max: {np.max(join_times):.4f} sim seconds")
    print(f"   Median: {np.median(join_times):.4f} sim seconds")

def graph_2_packet_delay():
    """Graph 2: End-to-end packet delay and path length."""
    data = read_csv("packet_log.csv")
    if not data:
        return
    
    delays = []
    hop_counts = []
    
    for row in data:
        if row.get('delay'):
            try:
                delay = float(row['delay'])
                delays.append(delay)
                
                # Calculate hop count from path
                path = row.get('path', '')
                if path:
                    # Path format might be comma-separated or list-like
                    path_list = path.strip('[]').split(',')
                    hop_count = len([p for p in path_list if p.strip()]) - 1
                    if hop_count >= 0:
                        hop_counts.append((hop_count, delay))
            except (ValueError, TypeError):
                continue
    
    if not delays:
        print("⚠️  No valid delay data found in packet_log.csv")
        return
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    
    # Histogram of delays
    ax1.hist(delays, bins=50, edgecolor='black', alpha=0.7, color='coral')
    ax1.set_xlabel('Packet Delay (simulation seconds)', fontsize=12)
    ax1.set_ylabel('Number of Packets', fontsize=12)
    ax1.set_title('Distribution of Packet Delays', fontsize=14, fontweight='bold')
    ax1.set_xlim(0, 0.001)  # Zoom in on small delay values
    ax1.axvline(np.mean(delays), color='red', linestyle='--', linewidth=2,
                label=f'Mean: {np.mean(delays):.6f}s')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    # Delay vs hop count
    if hop_counts:
        hop_dict = defaultdict(list)
        for hop, delay in hop_counts:
            hop_dict[hop].append(delay)
        
        hops = sorted(hop_dict.keys())
        avg_delays = [np.mean(hop_dict[h]) for h in hops]
        std_delays = [np.std(hop_dict[h]) for h in hops]
        
        ax2.errorbar(hops, avg_delays, yerr=std_delays, marker='o', 
                    linewidth=2, markersize=8, capsize=5, color='coral')
        ax2.set_xlabel('Hop Count', fontsize=12)
        ax2.set_ylabel('Average Delay (simulation seconds)', fontsize=12)
        ax2.set_title('Packet Delay vs Hop Count', fontsize=14, fontweight='bold')
        ax2.grid(True, alpha=0.3)
        ax2.set_xticks(hops)
    else:
        ax2.text(0.5, 0.5, 'No hop count data available', 
                ha='center', va='center', transform=ax2.transAxes)
    
    plt.tight_layout()
    plt.savefig('graph_2_packet_delay.png', dpi=300, bbox_inches='tight')
    print("✅ Graph 2 saved: graph_2_packet_delay.png")
    plt.close()
    
    # Print stats
    print(f"\n📊 Packet Delay Statistics:")
    print(f"   Average: {np.mean(delays):.4f} sim seconds")
    print(f"   Min: {np.min(delays):.4f} sim seconds")
    print(f"   Max: {np.max(delays):.4f} sim seconds")
    if hop_counts:
        print(f"   Average hop count: {np.mean([h for h, _ in hop_counts]):.2f}")

def graph_3_failure_recovery():
    """Graph 3: Failure & recovery - orphan count over time."""
    data = read_csv("failures.csv")
    if not data:
        return
    
    times = []
    orphan_counts = []
    event_types = []
    node_ids = []
    
    for row in data:
        try:
            time = float(row['time'])
            orphan_count = int(row['orphan_count'])
            event_type = row['event_type']
            node_id = row['node_id']
            
            times.append(time)
            orphan_counts.append(orphan_count)
            event_types.append(event_type)
            node_ids.append(node_id)
        except (ValueError, KeyError):
            continue
    
    if not times:
        print("⚠️  No valid failure data found in failures.csv")
        return
    
    fig, ax = plt.subplots(figsize=(12, 6))
    
    # Plot orphan count over time
    ax.plot(times, orphan_counts, 'b-', linewidth=2, alpha=0.7, label='Orphan Count')
    
    # Mark kill events
    kill_times = [t for t, et in zip(times, event_types) if et == 'KILLED']
    kill_orphans = [oc for oc, et in zip(orphan_counts, event_types) if et == 'KILLED']
    if kill_times:
        ax.scatter(kill_times, kill_orphans, color='red', marker='X', 
                  s=100, zorder=5, label='KILLED', edgecolors='black', linewidths=1)
    
    # Mark recovery events
    recover_times = [t for t, et in zip(times, event_types) if et == 'RECOVERED']
    recover_orphans = [oc for oc, et in zip(orphan_counts, event_types) if et == 'RECOVERED']
    if recover_times:
        ax.scatter(recover_times, recover_orphans, color='green', marker='o', 
                  s=100, zorder=5, label='RECOVERED', edgecolors='black', linewidths=1)
    
    # Mark energy death events
    energy_times = [t for t, et in zip(times, event_types) if et == 'ENERGY_DEAD']
    energy_orphans = [oc for oc, et in zip(orphan_counts, event_types) if et == 'ENERGY_DEAD']
    if energy_times:
        ax.scatter(energy_times, energy_orphans, color='orange', marker='s', 
                  s=80, zorder=5, label='ENERGY_DEAD', edgecolors='black', linewidths=1, alpha=0.7)
    
    ax.set_xlabel('Time (simulation seconds)', fontsize=12)
    ax.set_ylabel('Orphan Count', fontsize=12)
    ax.set_title('Orphan Count Over Time (Failure & Recovery)', fontsize=14, fontweight='bold')
    ax.legend(loc='best')
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('graph_3_failure_recovery.png', dpi=300, bbox_inches='tight')
    print("✅ Graph 3 saved: graph_3_failure_recovery.png")
    plt.close()
    
    # Print stats
    if kill_times and recover_times:
        print(f"\n📊 Failure & Recovery Statistics:")
        print(f"   First kill at: {min(kill_times):.2f} sim seconds")
        print(f"   First recovery at: {min(recover_times):.2f} sim seconds")
        print(f"   Max orphan count: {max(orphan_counts)}")
        if recover_times:
            recovery_duration = max(recover_times) - min(recover_times)
            print(f"   Recovery window: {recovery_duration:.2f} sim seconds")

def graph_4_energy_consumption():
    """Graph 4: Energy consumption by role and network lifetime."""
    data = read_csv("energy_metrics.csv")
    if not data or len(data) == 0:
        print("⚠️  No energy metrics data found in energy_metrics.csv")
        print("   Graph 4 not generated. Run the simulation to populate energy data.")
        # Create a placeholder graph with a message
        fig, ax = plt.subplots(figsize=(10, 6))
        ax.text(0.5, 0.5, 'No energy metrics data available.\nRun simulation to generate data.', 
                ha='center', va='center', transform=ax.transAxes, fontsize=14)
        ax.set_title('Energy Consumption by Role (No Data)', fontsize=14, fontweight='bold')
        plt.tight_layout()
        plt.savefig('graph_4_energy_consumption.png', dpi=300, bbox_inches='tight')
        print("   Created placeholder graph_4_energy_consumption.png")
        plt.close()
        return
    
    # Group by role
    role_energy = defaultdict(list)
    role_tx_energy = defaultdict(list)
    role_rx_energy = defaultdict(list)
    
    for row in data:
        role = row.get('role', 'UNKNOWN')
        try:
            total = float(row.get('total_energy_consumed_j', 0))
            tx = float(row.get('tx_energy_consumed_j', 0))
            rx = float(row.get('rx_energy_consumed_j', 0))
            
            if total > 0:
                role_energy[role].append(total)
                role_tx_energy[role].append(tx)
                role_rx_energy[role].append(rx)
        except (ValueError, TypeError):
            continue
    
    if not role_energy:
        print("⚠️  No valid energy data found in energy_metrics.csv")
        return
    
    fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(14, 10))
    
    # Energy consumption by role (total)
    roles = sorted(role_energy.keys())
    avg_energy = [np.mean(role_energy[r]) for r in roles]
    std_energy = [np.std(role_energy[r]) for r in roles]
    
    bars1 = ax1.bar(roles, avg_energy, yerr=std_energy, capsize=5, 
                    color=['black', 'blue', 'magenta', 'green', 'yellow'][:len(roles)],
                    alpha=0.7, edgecolor='black')
    ax1.set_xlabel('Node Role', fontsize=12)
    ax1.set_ylabel('Average Energy Consumed (J)', fontsize=12)
    ax1.set_title('Average Energy Consumption by Role', fontsize=14, fontweight='bold')
    ax1.tick_params(axis='x', rotation=45)
    ax1.grid(True, alpha=0.3, axis='y')
    
    # Add value labels on bars
    for bar, val in zip(bars1, avg_energy):
        height = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2., height,
                f'{val:.3f}', ha='center', va='bottom', fontsize=9)
    
    # TX vs RX energy by role
    roles_with_data = [r for r in roles if role_tx_energy[r] or role_rx_energy[r]]
    x = np.arange(len(roles_with_data))
    width = 0.35
    
    avg_tx = [np.mean(role_tx_energy[r]) if role_tx_energy[r] else 0 for r in roles_with_data]
    avg_rx = [np.mean(role_rx_energy[r]) if role_rx_energy[r] else 0 for r in roles_with_data]
    
    ax2.bar(x - width/2, avg_tx, width, label='TX Energy', color='steelblue', alpha=0.7, edgecolor='black')
    ax2.bar(x + width/2, avg_rx, width, label='RX Energy', color='coral', alpha=0.7, edgecolor='black')
    ax2.set_xlabel('Node Role', fontsize=12)
    ax2.set_ylabel('Average Energy (J)', fontsize=12)
    ax2.set_title('TX vs RX Energy by Role', fontsize=14, fontweight='bold')
    ax2.set_xticks(x)
    ax2.set_xticklabels(roles_with_data, rotation=45)
    ax2.legend()
    ax2.grid(True, alpha=0.3, axis='y')
    
    # Energy per packet
    total_energy = []
    total_packets = []
    tx_energy = []
    tx_packets = []
    rx_energy = []
    rx_packets = []
    
    for row in data:
        try:
            te = float(row.get('total_energy_consumed_j', 0))
            tp = int(row.get('total_packet_count', 0))
            txe = float(row.get('tx_energy_consumed_j', 0))
            txp = int(row.get('tx_packet_count', 0))
            rxe = float(row.get('rx_energy_consumed_j', 0))
            rxp = int(row.get('rx_packet_count', 0))
            
            if tp > 0:
                total_energy.append(te / tp)
            if txp > 0:
                tx_energy.append(txe / txp)
            if rxp > 0:
                rx_energy.append(rxe / rxp)
        except (ValueError, TypeError):
            continue
    
    if total_energy:
        categories = ['Total', 'TX', 'RX']
        values = [
            np.mean(total_energy) if total_energy else 0,
            np.mean(tx_energy) if tx_energy else 0,
            np.mean(rx_energy) if rx_energy else 0
        ]
        bars3 = ax3.bar(categories, values, color=['purple', 'steelblue', 'coral'], 
                       alpha=0.7, edgecolor='black')
        ax3.set_ylabel('Energy per Packet (J)', fontsize=12)
        ax3.set_title('Average Energy per Packet', fontsize=14, fontweight='bold')
        ax3.grid(True, alpha=0.3, axis='y')
        
        # Add value labels
        for bar, val in zip(bars3, values):
            if val > 0:
                height = bar.get_height()
                ax3.text(bar.get_x() + bar.get_width()/2., height,
                        f'{val:.6f}', ha='center', va='bottom', fontsize=9)
    
    # Cumulative dead nodes over time (from failures.csv)
    failure_data = read_csv("failures.csv")
    if failure_data:
        energy_dead_times = []
        for row in failure_data:
            if row.get('event_type') == 'ENERGY_DEAD':
                try:
                    energy_dead_times.append(float(row['time']))
                except (ValueError, TypeError):
                    continue
        
        if energy_dead_times:
            sorted_times = sorted(energy_dead_times)
            cumulative = np.arange(1, len(sorted_times) + 1)
            ax4.plot(sorted_times, cumulative, 'r-', linewidth=2, marker='o', markersize=4)
            ax4.set_xlabel('Time (simulation seconds)', fontsize=12)
            ax4.set_ylabel('Cumulative Dead Nodes (Energy)', fontsize=12)
            ax4.set_title('Cumulative Energy Deaths Over Time', fontsize=14, fontweight='bold')
            ax4.grid(True, alpha=0.3)
        else:
            ax4.text(0.5, 0.5, 'No energy death events', 
                    ha='center', va='center', transform=ax4.transAxes)
    else:
        ax4.text(0.5, 0.5, 'No failure data available', 
                ha='center', va='center', transform=ax4.transAxes)
    
    plt.tight_layout()
    plt.savefig('graph_4_energy_consumption.png', dpi=300, bbox_inches='tight')
    print("✅ Graph 4 saved: graph_4_energy_consumption.png")
    plt.close()
    
    # Print stats
    print(f"\n📊 Energy Consumption Statistics:")
    for role in roles:
        print(f"   {role}: Avg {np.mean(role_energy[role]):.6f} J "
              f"(TX: {np.mean(role_tx_energy[role]):.6f} J, "
              f"RX: {np.mean(role_rx_energy[role]):.6f} J)")

def graph_6_power_over_time():
    """Graph 6: Average node power over time."""
    data = read_csv("power_over_time.csv")
    if not data:
        print("⚠️  No power_over_time.csv found. Skipping power over time graph.")
        # Create placeholder
        fig, ax = plt.subplots(figsize=(12, 6))
        ax.text(0.5, 0.5, 'No power_over_time.csv data available.\nRun simulation to generate data.',
                ha='center', va='center', fontsize=14, transform=ax.transAxes)
        ax.set_title('Average Node Power Over Time', fontsize=16, fontweight='bold')
        plt.tight_layout()
        plt.savefig('graph_6_power_over_time.png', dpi=300, bbox_inches='tight')
        plt.close()
        return
    
    times = [float(row['time']) for row in data if row.get('time')]
    avg_powers = [float(row['avg_power_j']) for row in data if row.get('avg_power_j')]
    min_powers = [float(row['min_power_j']) for row in data if row.get('min_power_j')]
    max_powers = [float(row['max_power_j']) for row in data if row.get('max_power_j')]
    alive_nodes = [int(row['alive_nodes']) for row in data if row.get('alive_nodes')]
    dead_nodes = [int(row['dead_nodes']) for row in data if row.get('dead_nodes')]
    
    if not times or not avg_powers:
        print("⚠️  No power data found in power_over_time.csv")
        return
    
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10))
    
    # Plot 1: Average power over time with min/max bands
    ax1.plot(times, avg_powers, label='Average Power', linewidth=2, color='steelblue')
    ax1.fill_between(times, min_powers, max_powers, alpha=0.3, color='steelblue', label='Min-Max Range')
    ax1.axhline(y=1.7, color='r', linestyle='--', linewidth=1.5, label='Death Threshold (1.7 J)')
    ax1.set_xlabel('Simulation Time (seconds)', fontsize=12)
    ax1.set_ylabel('Power (Joules)', fontsize=12)
    ax1.set_title('Average Node Power Over Time', fontsize=14, fontweight='bold')
    ax1.legend(loc='best')
    ax1.grid(True, alpha=0.3)
    
    # Plot 2: Alive vs Dead nodes over time
    total_nodes = [a + d for a, d in zip(alive_nodes, dead_nodes)]
    ax2.plot(times, alive_nodes, label='Alive Nodes', linewidth=2, color='green')
    ax2.plot(times, dead_nodes, label='Dead Nodes', linewidth=2, color='red')
    ax2.fill_between(times, 0, alive_nodes, alpha=0.3, color='green')
    ax2.fill_between(times, alive_nodes, total_nodes, alpha=0.3, color='red')
    ax2.set_xlabel('Simulation Time (seconds)', fontsize=12)
    ax2.set_ylabel('Number of Nodes', fontsize=12)
    ax2.set_title('Node Survival Over Time', fontsize=14, fontweight='bold')
    ax2.legend(loc='best')
    ax2.grid(True, alpha=0.3)
    ax2.set_ylim(bottom=0)
    
    plt.tight_layout()
    plt.savefig('graph_6_power_over_time.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("✅ Graph 6: Power over time saved to graph_6_power_over_time.png")


def graph_5_packet_loss():
    """Graph 5: Packet loss - configured vs realized."""
    # Try to read from saved stats file first
    stats_data = read_csv("packet_loss_stats.csv")
    if stats_data and len(stats_data) > 0:
        row = stats_data[0]
        configured_loss = float(row.get('configured_loss_pct', 0))
        realized_loss = float(row.get('realized_loss_pct', 0))
        attempts = int(row.get('attempts', 0))
        dropped = int(row.get('dropped', 0))
    else:
        # Fallback: try to read from config
        try:
            from source import config
            configured_loss = getattr(config, 'PACKET_LOSS_RATIO', 0.01) * 100
        except:
            configured_loss = 1.0  # Default fallback
        realized_loss = configured_loss  # Placeholder if no data
        attempts = 0
        dropped = 0
    
    fig, ax = plt.subplots(figsize=(8, 6))
    
    categories = ['Configured\nLoss', 'Realized\nLoss']
    values = [configured_loss, realized_loss]
    colors = ['steelblue', 'coral']
    
    bars = ax.bar(categories, values, color=colors, alpha=0.7, edgecolor='black', width=0.5)
    ax.set_ylabel('Packet Loss (%)', fontsize=12)
    ax.set_title('Packet Loss: Configured vs Realized', fontsize=14, fontweight='bold')
    ax.set_ylim(0, max(values) * 1.2 if values else 10)
    ax.grid(True, alpha=0.3, axis='y')
    
    # Add value labels
    for bar, val in zip(bars, values):
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'{val:.2f}%', ha='center', va='bottom', fontsize=12, fontweight='bold')
    
    plt.tight_layout()
    plt.savefig('graph_5_packet_loss.png', dpi=300, bbox_inches='tight')
    print("✅ Graph 5 saved: graph_5_packet_loss.png")
    print(f"   Configured: {configured_loss:.2f}%")
    print(f"   Realized: {realized_loss:.2f}%")
    if attempts > 0:
        print(f"   Attempts: {attempts}, Dropped: {dropped}")
    plt.close()

def main():
    """Generate all graphs."""
    print("=" * 60)
    print("Generating Network Simulation Graphs")
    print("=" * 60)
    
    # Check if we're in the right directory
    if not os.path.exists("registration_log.csv"):
        print("⚠️  Warning: CSV files not found in current directory.")
        print("   Please run this script from the wsnlab/ directory")
        return
    
    print("\n📊 Generating graphs...\n")
    
    try:
        graph_1_join_times()
        graph_2_packet_delay()
        graph_3_failure_recovery()
        graph_4_energy_consumption()
        graph_5_packet_loss()
        graph_6_power_over_time()
        
        print("\n" + "=" * 60)
        print("✅ All graphs generated successfully!")
        print("=" * 60)
        print("\nGenerated files:")
        print("  - graph_1_join_times.png")
        print("  - graph_2_packet_delay.png")
        print("  - graph_3_failure_recovery.png")
        print("  - graph_4_energy_consumption.png")
        print("  - graph_5_packet_loss.png")
        print("  - graph_6_power_over_time.png")
        
    except Exception as e:
        print(f"\n❌ Error generating graphs: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()

